stages:
- build

builder:
    stage: build
    image: debian:12
    script:
        - apt-get update
        - apt-get install -y --install-recommends --fix-missing nodejs npm git curl wget dpkg rpm zip unzip
        - npm install .
        - npm run make
        - npm run make-darwin
    artifacts:
        paths:
            - ./out/make/*