stages:
- build

builder:
    stage: build
    image: debian:12
    script:
        - apt-get update
        - apt-get upgrade -y
        - apt-get install -y --install-recommends --fix-missing nodejs npm curl wget dpkg rpm zip unzip
        - apt-get install -y --install-recommends --fix-missing wine mono-complete
        - npm install .
        - npm run make-linux
        - npm run make-darwin
        - npm run make-win
        - cd ./docker && zip -r ./../out/make/docker.zip ./* && cd ..
    artifacts:
        paths:
            - ./out/make/deb/x64/*.deb
            - ./out/make/rpm/x64/*.rpm
            - ./out/make/squirrel.windows/x64/*.exe
            - ./out/make/zip/darwin/x64/*.zip
            - ./out/make/zip/linux/x64/*.zip
            - ./out/make/zip/win32/x64/*.zip
            - ./out/make/docker.zip
    tags:
        - docker