# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/pipeline/#customization
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
stages:
- build
- test
- deploy
- review
- dast
- staging
- canary
- production
- incremental rollout 10%
- incremental rollout 25%
- incremental rollout 50%
- incremental rollout 100%
- performance
- cleanup
sast:
    stage: test
include:
- template: Auto-DevOps.gitlab-ci.yml
      
builder:
    stage: build
    image: debian:12
    script:
        - echo 'deb http://deb.debian.org/debian/ stable main contrib non-free' >> /etc/apt/sources.list
        - apt-get update && apt-get upgrade && apt-get install -y nodejs npm git curl wget wine mono-complete dpkg rpm zip unzip
        - npm install .
        - npm run make
        - npm run make-win
        - npm run make-darwin
    artifacts:
        paths:
            - ./out/make/*
    only:
        - tags
        - triggers