const debugMode = process.env.NOVAMPP_DEBUG === '1';
const forceDocker = process.env.NOVAMPP_FORCE_DOCKER === '1';
const forceMenu = process.env.NOVAMPP_FORCE_MENU === '1';
const { app, BrowserWindow, Tray, Menu, dialog, ipcMain } = require('electron');
const { exec } = require('child_process');
const path = require('path');
const literalpath = process.platform === 'win32' ? path.join(process.env.LOCALAPPDATA, 'NovAMPP') : process.platform === 'linux' ? '/usr/local/novampp' : '/usr/local/novampp';
const axios = require('axios');
const fs = require('fs');
const iconPath = path.join(__dirname, './src/main/favicon.png');
const installdocker = require('./scripts/installdocker');
const { isDockerInstalled, registeripc } = require('./scripts/ipc');
const unzipper = require('unzipper');
async function startupchecks() {
    if (process.platform === 'win32') {
        const icoData = 'AAABAAUAEBAAAAEAIABoBAAAVgAAABgYAAABACAAiAkAAL4EAAAgIAAAAQAgAKgQAABGDgAAMDAAAAEAIACoJQAA7h4AAAAAAAABACAAtBoAAJZEAAAoAAAAEAAAACAAAAABACAAAAAAAAAEAAAjLgAAIy4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/AIIA/wCCBP8Aggj/AIIC/wCCAP8AggD/AIIB/wCCB/8Aggj/AIID/wCCAAAAAAAAAAAAAAAAAAAAAAAAAAAA/wCCAP8Agjz/AIK4/wCCQP8AggD/AIIA/wCCFv8AgqX/AILA/wCCT/8AggD9AIIAAAAAAAAAAAAAAAAAAAAAAP8AggD/AIIq/wCC6v8Agon/AIIA/wCCAP8Agi7/AILr/wCC//8Agpz8AIIB/gCCAAAAAAAAAAAAAAAAAAAAAAD/AIIA/wCCCv8Agr//AILD/wCCDP8AggD/AIJH/wCC7/8Agtf/AILQ/wCCFf8AggAAAAAAAAAAAAAAAAAAAAAA/wCBAP8AggD/AIKE/wCC6/8Agiz/AIIA/wCCZf8Aguf/AIKP/wCC7v8Agj3/AIIAAAAAAAAAAAAAAAAAAAAAAAAAAAD/AIIA/wCCSP8AgvX/AIJg/wCCAP8AgoT/AILa/wCCTv8Agu7/AIJ1/wCCAP4AggAAAAAAAAAAAAAAAAAAAAAA/wCCAP8Aghz/AILe/wCCnfwAgQH/AIKk/wCCxf8Agh3/AILO/wCCsv4Aggb+AIIAAAAAAAAAAAAAAAAAAAAAAP8AgQD/AIEE/wCCrP8AgtP/AIId/wCCwP8Agqr8AIAC/wCCl/8AguL/AIIg/wCCAAAAAAAAAAAAAAAAAAAAAAD/AIEA/wCCAP8Agm//AILw/wCCTv8AgtX/AIKK/wCCAP8Aglv/AIL2/wCCTv8AggAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AggD/AII4/wCC7f8AgpD/AILk/wCCav8AggD/AIIo/wCC6f8Agor/AIIA/gCCAAAAAAAAAAAAAAAAAAAAAAD/AIIA/wCCEv8Agsz/AILY/wCC7/8Agkz/AIIA/wCCCv8Agr7/AILE/wCCDP8AggAAAAAAAAAAAAAAAAAAAAAA/wCBAP8AqQD/AIKW/wCC//8Agu3/AIIx/wCCAP8AggD/AIKD/wCC7f8Agi7/AIIAAAAAAAAAAAAAAAAAAAAAAP8AgQD/AIIA/wCCSv8Agrz/AIKk/wCCF/8AggD/AIIA/wCCPP8Agrj/AIJA/wCCAAAAAAAAAAAAAAAAAAAAAAAAAAAA/wCCAP8AggL/AIIH/wCCBv8AggH/AIIA/wCCAP8AggL/AIII/wCCBP8AggAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//AADGHwAAxh8AAMYPAADCDwAA4g8AAOIPAADgBwAA4AcAAPBHAADwRwAA8EMAAPhjAAD4YwAA+GMAAP//AAAoAAAAGAAAADAAAAABACAAAAAAAAAJAAAjLgAAIy4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/AIIA/wCCAf8AggL/AIIC/gCCAf8AggAAAAAAAAAAAP0AgQD9AIEA/wCCAv8AggL/AIIC/wCCAf8AggAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/AIIA/wCCFf8AgpT/AIKq/wCCRP8AggD+AIIAAAAAAP8AggD/AIIP/wCCjf8Agqr/AIKq/wCCWf8AggD+AIIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/AIIA/wCBC/8Agr7/AIL//wCClf8AggD+AIIAAAAAAP8AggD/AIIm/wCC5f8Agv//AIL//wCCs/4Aggf+AIIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/AIEA/wCDAP8AgoP/AIL//wCCy/4AghH+AIIAAAAAAP8AggD/AII9/wCC9P8Agv7/AIL//wCC4P8AgiP/AIIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/wCCAP8Agkn/AIL4/wCC7/8Agjf/AIIAAAAAAP8AggD/AIJY/wCC//8AguH/AILh/wCC/P8AglL/AIIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/wCCAP8Agh3/AILb/wCC//8Agm3/AIIA/QCCAP8AggD/AIJ2/wCC//8Agrj/AIKw/wCC//8Ago3/AIIA/gCCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/wCBAP8AgQT/AIKq/wCC//8Agqj+AIIE/gCCAP8AhAD/AIKV/wCC//8AgpT/AIJ8/wCC//8AgsT+AIIO/gCCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/wCBAP8AggD/AIJv/wCC//8Agtn/AIIb/wCCAP4AgQX/AIKy/wCC//8AgnT/AIJI/wCC+v8Aguz/AIIx/wCCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AggD/AII5/wCC8P8Agvf/AIJH/wCCAP4AghD/AILM/wCC//8Aglj/AIId/wCC4P8Agv//AIJl/wCCAP4AggAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AggD/AIET/wCCzP8Agv//AIKB/wCCAP8AgiD/AILh/wCC9v8Agj3+AIED/wCCs/8Agv//AIKg/QCCAv4AggAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AgQD/AHQA/wCCl/8Agv//AIK6/gCCBv8Agjb/AILy/wCC5/8Agib/AIIA/wCCef8Agv//AILT/wCCF/8AggAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AfwD/AIIA/wCCXP8Agv7/AILl/wCCI/8Agk7/AIL+/wCC0v4AghT/AIIA/wCCQP8AgvT/AIL0/wCCQP8AggAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/AIIA/wCCKv8Aguf/AIL8/wCCT/8Agmr/AIL//wCCuf4AgQj+AIIA/wCCF/8AgtP/AIL//wCCef8AggD+AIIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/AIEA/wCBCv8Agrz/AIL//wCCg/8Agor/AIL//wCCnOYAbAD+AIEA/QCAAv8AgqD/AIL//wCCs/4Aggf+AIIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/AIEA/wCDAP8AgoT/AIL//wCCt/8AgrH/AIL//wCCff8AggD+AIEA/wCCAP8AgmX/AIL//wCC4P8AgiP/AIIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/wCCAP8Agkr/AIL5/wCC5f8Agt7/AIL//wCCXv8AggAAAAAA/wCCAP8AgjD/AILr/wCC+/8AglL/AIIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/wCCAP8Agh3/AILb/wCC//8Agv3/AIL2/wCCQv8AggAAAAAA/wCCAP4Agg7/AILE/wCC//8Ago3/AIIA/gCCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/wCBAP8AgQT/AIKr/wCC//8Agv//AILp/wCCKv8AggAAAAAA/gCBAP8AhAD/AIKN/wCC//8Agsb+AIIP/gCCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/wCBAP8AggD/AIJQ/wCCpf8AgqX/AIKM/wCCEf8AggAAAAAA/QCAAP8AggD/AII+/wCCp/8Agpf/AIIZ/wCCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AggD/AIEA/wCCAf8AggH/AIIB/QCAAPwAgAAAAAAAAAAAAP0AgQD9AIEA/gCBAv4AgQL/AIIB/wCCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////AP///wDh8P8A4eD/AOHgfwDw4H8A8OB/APDgfwDwYD8A+EA/APhAPwD4QB8A/AIfAPwCHwD8Ah8A/AYPAP4HDwD+Bw8A/gcPAP4HhwD/B4cA/4/HAP///wD///8AKAAAACAAAABAAAAAAQAgAAAAAAAAEAAAIy4AACMuAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AgQD/AIEA/wCBAP8AgQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/wCBAP8AgQP/AIJk/wCClP8AgpP/AIJE/wCCAP4AggAAAAAAAAAAAAAAAAD+AIIA/gCCCv8Agnb/AIKT/wCCkf8AgpP/AIJc/ACCAf4AggAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/AIEA/wCDAP8Agob/AIL//wCC//8AgqL9AIIC/gCCAAAAAAAAAAAAAAAAAP4AggD/AIIe/wCC3v8Agv//AIL//wCC//8Agsf+AIIQ/gCCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/AIIA/wCCS/8Agvf/AIL//wCC1P4Aghj+AIIAAAAAAAAAAAAAAAAA/wCCAP8AgjP/AILu/wCC//8Agv//AIL//wCC7f8AgjT/AIIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AggD/AIIe/wCC2/8Agv//AIL0/wCCQv8AggAAAAAAAAAAAAAAAAD/AIIA/wCCTf8Agvn/AIL//wCC+/8Agv7/AIL//wCCaf8AggD+AIIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/wCBAP8AgQX/AIKr/wCC//8Agv//AIJ7/wCCAP4AggAAAAAA/gCBAP8AggD/AIJq/wCC//8Agv//AILM/wCC9P8Agv//AIKk/QCCA/4AggAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/AIAA/wCCAP8AgnH/AIL//wCC//8AgrT+AIII/gCCAAAAAAD+AIEA/wCDAP8Agon/AIL//wCC/f8Ago3/AILf/wCC//8Agtb+AIIa/gCCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/AIIA/wCCOv8AgvD/AIL//wCC4f8AgiT/AIIAAAAAAP4AgQD9AIAC/wCCp/8Agv//AIL4/wCCWf8Agr//AIL//wCC9f8AgkT/AIIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AgQD/AIET/wCCzf8Agv//AIL6/wCCVP8AggD6AIIA/gCBAP4AgQv/AILC/wCC//8Agu7+AIIy/wCClf8Agv//AIL//wCCff8AggD+AIIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/wCBAP8AfAH/AIKY/wCC//8Agv//AIKP/wCCAP4AggD+AIEA/gCBGv8Agtn/AIL//wCC3f4AgRn/AIJl/wCC//8Agv//AIK3/gCCCP4AggAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/AIAA/wCCAP8Agl3/AIL9/wCC//8AgsX+AIIP/gCCAP8AggD/AIIt/wCC6/8Agv//AILG/gCBCv8Agjb/AILv/wCC//8AguP+AIIm/wCCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/AIIA/wCCK/8Aguf/AIL//wCC7P8AgjL/AIIA/wCCAP8Agkb/AIL3/wCC//8Agqv9AIAC/gCCEv8Agsz/AIL//wCC+/8Aglb/AIIA/ACCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AgQD/AIEL/wCCvf8Agv//AIL+/wCCZ/8AggD/AIIA/wCCYv8Agv//AIL//wCCjf8AgwD2AHkA/wCCl/8Agv//AIL//wCCkf8AggD+AIIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/wCBAP8AgwD/AIKF/wCC//8Agv//AIKi/QCCAv8AggD/AIKA/wCC//8Agv//AIJu/wCCAP8AggD/AIJc/wCC/P8Agv//AILI/gCCEP4AggAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/wCCAP8Agkv/AIL3/wCC//8AgtT+AIIY/wCGAP8Agp//AIL//wCC+v8AglD/AIIA/wCCAP8Agir/AILm/wCC//8Agu3/AII0/wCCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/AIIA/wCCHv8Agtv/AIL//wCC8/8Agj79AIEF/wCCu/8Agv//AILw/wCCNv8AggD+AIEA/gCBC/8Agrz/AIL//wCC//8Agmn/AIIA/gCCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AgQD/AIEF/wCCrP8Agv//AIL//wCCcP4AgRL/AILT/wCC//8AguD+AIIg/gCCAP4AgQD/AIMA/wCChP8Agv//AIL//wCCpf0AggP+AIIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/wCAAP8AggD/AIJx/wCC//8Agv//AIKh/gCCKv8Agub/AIL//wCCyv4AgRD+AIEAAAAAAP8AggD/AIJK/wCC9/8Agv//AILW/gCCGv4AggAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/wCCAP8Agjr/AILw/wCC//8Agsr/AIJR/wCC8/8Agv//AIKw/gCBBf4AgQAAAAAA/wCCAP8Agh3/AILa/wCC//8AgvX/AIJE/wCCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/AIEA/wCBFP8Ags3/AIL//wCC5v8Agon/AIL6/wCC//8AgpL/AIQA/gCBAAAAAAD+AIEA/gCBBf8Agqv/AIL//wCC//8Agn3/AIIA/gCCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AgQD/AH0B/wCCmf8Agv//AIL4/wCCzP8Agv7/AIL//wCCc/8AggD+AIEAAAAAAP0AgAD/AIIA/wCCcP8Agv//AIL//wCCt/4Aggj+AIIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/wCAAP8AggD/AIJe/wCC/f8Agv//AIL7/wCC//8Agvz/AIJV/wCCAAAAAAAAAAAAAAAAAP8AggD/AII5/wCC8P8Agv//AILj/wCCJv8AggAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/wCCAP8Agiv/AILn/wCC//8Agv//AIL//wCC8v8Agjr/AIIAAAAAAAAAAAAAAAAA/gCBAP4AgRP/AILM/wCC//8Agvv/AIJW/wCCAP0AggAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/AIEA/wCBC/8Agr7/AIL//wCC//8Agv//AILj/gCCI/4AggAAAAAAAAAAAAAAAAD+AIEA9gB5AP8Agpf/AIL//wCC//8AgpP/AIIA/gCCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AgQD/AIoA/wCCUf8Agoz/AIKK/wCCjP8AgnT+AIIM/gCBAAAAAAAAAAAAAAAAAP0AgAD/AIIA/wCCPf8AgpD/AIKS/wCCav4AggX+AIIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP4AggD+AIIA/gCCAP4AggAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/////////////////////8H4D//g+A//4PgP/+D4D//g+Af/8HgH//BwB//wcAf/8HAD//gwA//4MAP/+DDD//wQwf/8EMH//ADB//wA4P/+AOD//gDg//4B4P/+AfB//wHwf/8B8H//Afh//4H4P/////////////////////ygAAAAwAAAAYAAAAAEAIAAAAAAAACQAACMuAAAjLgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/AIEA/wCBFv8Agl7/AIJk/wCCY/8AgmX/AII88ACCAP4AggAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/gCBAP4AgQT/AIJJ/wCCZP8AgmL/AIJi/wCCYv8AgmP/AIJR/gCCCP4AggAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/AIEA/wCBIP8Agtz/AIL//wCC//8Agv//AIK6/gCCC/4AggAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/gCBAP4AgRL/AILM/wCC//8Agv//AIL+/wCC/v8Agv//AILm/gCCLP4AggAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/AIEA/wCBBv8Agq3/AIL//wCC//8Agv//AILl/gCCKv4AggAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/gCBAP4AgSP/AILh/wCC//8Agv//AIL//wCC//8Agv//AIL9/wCCX/8AggD+AIIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/AIEA/wCCAP8AgnP/AIL//wCC//8Agv//AIL8/wCCW/8AggD+AIIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/gCBAP4AgTn/AILx/wCC//8Agv//AIL//wCC//8Agv//AIL//wCCmvsAggH+AIIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/wCCAP8AgTz/AILx/wCC//8Agv//AIL//wCClvcAggH+AIIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/wCCAP4AglP/AIL7/wCC//8Agv//AIL//wCC//8Agv//AIL//wCCzv4AghX+AIIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/wCBAP8AgRX/AILO/wCC//8Agv//AIL//wCCy/4AghP+AIIAAAAAAAAAAAAAAAAAAAAAAAAAAAD9AIEA/wCCAP8AgnD/AIL//wCC//8Agv//AIL6/wCC+/8Agv//AIL//wCC8P4Agjv/AIIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/wCBAP8AfgH/AIKb/wCC//8Agv//AIL//wCC7/4Agjj/AIIAAAAAAAAAAAAAAAAAAAAAAAAAAAD+AIEA/wCEAP8Ago//AIL//wCC//8Agv//AILY/wCC2v8Agv//AIL//wCC//8AgnL/AIIA/gCCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/wCBAP8AggD/AIJg/wCC/f8Agv//AIL//wCC//8Agm7/AIIA/gCCAAAAAAAAAAAAAAAAAAAAAAD+AIEA/QCABP8Agqz/AIL//wCC//8Agv//AIKv/wCCrP8Agv//AIL//wCC//8Agqz+AIIG/gCCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AgQD/AIEt/wCC6P8Agv//AIL//wCC//8Agqn9AIIF/gCCAAAAAAAAAAAAAAAAAAAAAAD+AIEA/gCBD/8Agsf/AIL//wCC//8Agv//AIKL/wCCff8Agv//AIL//wCC//8Agtz+AIIf/gCCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AgQD/AIEM/wCCv/8Agv//AIL//wCC//8Agtn+AIId/gCCAAAAAAAAAAAAAAAAAAAAAAD+AIEA/gCBHv8Agtz/AIL//wCC//8Agv//AIJr/wCCUP8Agvr/AIL//wCC//8Agvf/AIJM/wCCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AgQD/AIQA/wCCh/8Agv//AIL//wCC//8Agvb/AIJJ/wCCAAAAAAAAAAAAAAAAAAAAAAD/AIIA/gCCM/8Agu3/AIL//wCC//8Agvr+AIJO/wCCKf8Agun/AIL//wCC//8Agv//AIKG/wCCAP4AggAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/AIIA/wCCTf8Agvj/AIL//wCC//8Agv//AIKC/wCCAP4AggAAAAAAAAAAAAAAAAD/AIIA/wCCTP8Agvn/AIL//wCC//8AgvD+AIE2/gCBDv8Agsr/AIL//wCC//8Agv//AIK+/gCCDP4AggAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/AIEA/wCBIP8Agtz/AIL//wCC//8Agv//AIK7/gCCC/4AggAAAAAAAAAAAP4AgQD/AIIA/wCCaf8Agv//AIL//wCC//8Agt/+AIEh/wCHAP8Agp3/AIL//wCC//8Agv//AILn/gCCLP4AggAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/AIEA/wCBBv8Agq3/AIL//wCC//8Agv//AILl/gCCKv4AggAAAAAAAAAAAP4AgQD/AIMA/wCCh/8Agv//AIL//wCC//8Agsr+AIER/wCCAP8Agmr/AIL//wCC//8Agv//AIL9/wCCX/8AggD+AIIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/AIEA/wCCAP8AgnP/AIL//wCC//8Agv//AIL8/wCCW/8AggD+AIIAAAAAAP4AgQD8AIAD/wCCpf8Agv//AIL//wCC//8AgrD9AIEF/wCCAP8Agjj/AILv/wCC//8Agv//AIL//wCCmvoAggH+AIIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/wCCAP8AgTz/AILx/wCC//8Agv//AIL//wCClvYAggH+AIIAAAAAAP4AgQD+AIEL/wCCwP8Agv//AIL//wCC//8AgpP/AIYA/gCBAP4AgRT/AILN/wCC//8Agv//AIL//wCCzv4AghX+AIIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/wCBAP8AgRX/AILP/wCC//8Agv//AIL//wCCy/4AghP+AIIAAAAAAP4AgQD+AIEZ/wCC1/8Agv//AIL//wCC//8AgnT/AIIA/gCBAPsAfgH/AIKZ/wCC//8Agv//AIL//wCC8P4Agjz/AIIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/wCBAP8AfgH/AIKb/wCC//8Agv//AIL//wCC7v4Agjj/AIIAAAAAAP4AggD+AIIt/wCC6f8Agv//AIL//wCC+/4Aglb/AIIA/gCBAP8AggD/AIJe/wCC/P8Agv//AIL//wCC//8AgnL/AIIA/gCCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/wCBAP8AggD/AIJg/wCC/f8Agv//AIL//wCC//8Agm7/AIIA/gCCAP8AggD+AIJF/wCC9v8Agv//AIL//wCC8v4Agjv/AIIAAAAAAP8AggD+AIEs/wCC5/8Agv//AIL//wCC//8Agq39AIIG/gCCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AgQD/AIEt/wCC6P8Agv//AIL//wCC//8Agqn9AIIF/gCCAP8AggD+AIJh/wCC/v8Agv//AIL//wCC4v4AgST+AIEAAAAAAP4AgQD+AIEM/wCCvf8Agv//AIL//wCC//8Agtz+AIIf/gCCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AgQD/AIEN/wCCv/8Agv//AIL//wCC//8Agtj+AIIc/gCCAP8AggD/AIJ//wCC//8Agv//AIL//wCCzv4AgRP+AIEAAAAAAP4AgQD/AIMA/wCChv8Agv//AIL//wCC//8Agvf+AIJN/wCCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AgQD/AIQA/wCCiP8Agv//AIL//wCC//8AgvX/AIJG/wCCAPkAfQH/AIKd/wCC//8Agv//AIL//wCCtP4AgQf+AIEAAAAAAAAAAAD/AIIA/wCCTP8Agvf/AIL//wCC//8Agv//AIKG/wCCAP4AggAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/AIIA/wCCTv8Agvj/AIL//wCC//8Agv//AIJ5/wCCAP4AgQn/AIK5/wCC//8Agv//AIL//wCCl/8AuwD+AIEAAAAAAAAAAAD+AIEA/gCBH/8Agtv/AIL//wCC//8Agv//AIK+/gCCDP4AggAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/AIEA/wCBIP8Agt3/AIL//wCC//8Agv//AIKs/QCABP4AgRX/AILS/wCC//8Agv//AIL//wCCef8AggD+AIEAAAAAAAAAAAD+AIEA/gCBBf8Agqz/AIL//wCC//8Agv//AILn/gCCLP4AggAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/AIEA/wCBBv8Agq7/AIL//wCC//8Agv//AILW/gCBF/4Agib/AILl/wCC//8Agv//AIL9/wCCWv8AggAAAAAAAAAAAAAAAAD+AIEA/wCCAP8AgnL/AIL//wCC//8Agv//AIL9/gCCX/8AggD+AIIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/AIEA/wCCAP8AgnT/AIL//wCC//8Agv//AILx/wCCN/4Agjv/AILz/wCC//8Agv//AILz/gCCP/4AggAAAAAAAAAAAAAAAAAAAAAA/wCCAP8Agjv/AILw/wCC//8Agv//AIL//wCCmvsAggH+AIIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/wCCAP8Agj3/AILx/wCC//8Agv//AIL+/wCCYv4AglX/AIL8/wCC//8Agv//AILl/gCBJ/4AgQAAAAAAAAAAAAAAAAAAAAAA/gCBAP4AgRT/AILN/wCC//8Agv//AIL//wCCzv4AghX+AIIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/wCBAP8AgRX/AILP/wCC//8Agv//AIL//wCCkf8Agnf/AIL//wCC//8Agv//AILS/gCBFf4AgQAAAAAAAAAAAAAAAAAAAAAA/gCBAPoAfQH/AIKZ/wCC//8Agv//AIL//wCC8P4Agjz+AIIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/wCBAP8AfwH/AIKb/wCC//8Agv//AIL//wCCvv8AgqD/AIL//wCC//8Agv//AIK5/gCBCf4AgQAAAAAAAAAAAAAAAAAAAAAA/gCBAP8AggD/AIJe/wCC/P8Agv//AIL//wCC//8AgnL/AIIA/gCCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/wCBAP8AggD/AIJh/wCC/f8Agv//AIL//wCC5P8AgtL/AIL//wCC//8Agv//AIKc+QB+Af4AgQAAAAAAAAAAAAAAAAAAAAAAAAAAAP4AggD+AIEs/wCC5/8Agv//AIL//wCC//8Agq39AIIG/gCCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AgQD/AIEu/wCC6P8Agv//AIL//wCC/P8Agvr/AIL//wCC//8Agv//AIJ+/wCCAP4AgQAAAAAAAAAAAAAAAAAAAAAAAAAAAP4AgQD+AIEM/wCCvf8Agv//AIL//wCC//8Agtz+AIIf/gCCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AgQD/AIEN/wCCv/8Agv//AIL//wCC//8Agv//AIL//wCC//8Agv7/AIJf/wCCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP4AgQD/AIMA/wCChv8Agv//AIL//wCC//8Agvf+AIJN/wCCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AgQD/AIQA/wCCiP8Agv//AIL//wCC//8Agv//AIL//wCC//8AgvX+AIJD/wCCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/AIIA/wCCTP8Agvf/AIL//wCC//8Agv//AIKG/wCCAP4AggAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/AIIA/wCCTv8Agvj/AIL//wCC//8Agv//AIL//wCC//8Aguj+AIEr/gCBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD+AIEA/gCBH/8Agtv/AIL//wCC//8Agv//AIK+/gCCDP4AggAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/AIEA/wCBIP8Agtr/AIL+/wCC/P8Agvz/AIL9/wCC//8AgtP+AIEY/gCBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD+AIEA/gCBBf8Agqv/AIL//wCC/v8Agv//AILn/gCCLf4AggAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/AIEA/wCBBf8AgkP/AIJZ/wCCWP8Aglj/AIJZ/wCCW/8Agkf+AIEF/gCBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD+AIEA/wCDAP8AgjT/AIJh/wCCYP8AgmH/AIJe/wCCHP8AggAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///////8AAP///////wAA////////AAD///////8AAP///////wAA////////AAD+B/4A//8AAP4D/gD//wAA/gP+AP//AAD/A/4Af/8AAP8B/gB//wAA/wH+AH//AAD/Af4Af/8AAP+B/AA//wAA/4D8AD//AAD/gPwAP/8AAP/A/AA//wAA/8D8AB//AAD/wHwIH/8AAP/AfAgf/wAA/+B4CA//AAD/4DgYD/8AAP/gOBgP/wAA/+A4HA//AAD/8DgcB/8AAP/wGBwH/wAA//AYHgf/AAD/+BAeB/8AAP/4ED4D/wAA//gAPgP/AAD/+AA/A/8AAP/8AD8B/wAA//wAPwH/AAD//AA/Af8AAP/8AD+B/wAA//4AP4D/AAD//gB/gP8AAP/+AH/A/wAA//8Af8D/AAD//wB/wH8AAP//AH/AfwAA//8Af+B/AAD///////8AAP///////wAA////////AAD///////8AAP///////wAA////////AACJUE5HDQoaCgAAAA1JSERSAAABAAAAAQAIBgAAAFxyqGYAABp7SURBVHja7Z1Lc1VXeoaf7+gKNncwIPmG7ca0GxoQySCDDJNhfkZ+Q1dfdLFHqWSYcYZdlVkmmSZVmSUxxm6DbXxtuxsJMNjCIEAgafVg7QMHoSOdy/7Wvr1PFcVFsPdaB533rL2+d70fCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQ4nms6AEIkZpZHpthrT7+ybbvkxaGsflyAWB9llYoer7bMVr0AJrEAmEK+FuD3Zu+ZD38bH3+/R1+DneB/5yldb3o1yUlC2yMA/8A/M2m12TT67Pj1zb/uvP3LeAr4N+AH4qe83ZIANLy98A/Ay90+XovK7Kd/o718OcWYAn4EmiUAACHgH807O+c7/N7YK3oye6EBCAR84RdwF8bHC56LBn7geNFD6IATgA/871FWAXeh7W7RU92J/p5DhJDYPAScLbocXQwCUz9jkeN2Qf6NQ8M+CVw1PlWt4EPZxkv9fM/SABS8hbwRtGDaGPYmMHLY4yMFT2WVEwwsRu4YNgu51t9RXy8Kj0SgATMEVrAOeLzZ2kIMBWwyaLHkZCjwBnfW4QAfATh+6In2wsSgAS0YA9wwWC86LFs4ijdNyTryEngded7rADvzzLysOjJ9oIEIA1TwDtFD2ILjhA3A2vPPOsjwHnDDjrf6jpwuej59ooEIA0/B14pehBbsJ/yVCVcMWwvcB7w3vP4DPiu6Pn2igTAmXnCGDBjsK/osWzBHvx3xMvCy7ivwsI6cAnCj0VPtlckAM4YHCB+8owUPZYtmASm3o3lsbrzDlEEPLkDfDDLSOkNQG0kAP68Brxd9CC6MAZMB8ZrbQibZ30cuEBc8XjyHfBp0fPtBwmAP2eAY0UPogsGTIFNFD0Q30naIeBcnweA+iQAXAEWi55vP0gAHFkgZMaTcpbaDMOiHbiU48uRE8QSoCerwEVYWyl6sv0gAfDlCOWy/z5HiGMs4wZlLrTtv4a95HyrW0T770bRc+4HCYAvpbL/duEAJXMo5knb/gt423+/piL2304kAE7MltT+uwV1LwXK/rsNEgAnRuIba6aE9t/N7CI6FevKSeIegCcrwMWq2H87kQD4MQWcLnoQO2HYGDC9wHrtSoFzrI0QV2EHnG91Hfi46PkOggTAj7LafzfTAqbrWAps0dpLPP6bwP4bvi16voMgAXCgw/67t+ix9Mgxns8prAMJ7b8sFz3ZQZAAOFBy++9WHKE6YtUP7wDTzveonP23EwmAD6/hbzzJk4OUv1rRFwtsTBCX/7L/boMEwIczVChwM3tU8TbKpOYgcQPQ+3v8CoSloic7KBKAnMnSf0tr/92KEJ//61YKTJX+exE27hU92UGRAORMlv77y6LH0SfjwNR8LJtVnt+yasAZwxKl/45Vyv7biQQgf94C3ix6EP2QnZKbNlplNy31xCijqey/lUn/7YYEIEcy++9ZHDbUAmEtEL4PBJdPG4PjVpNSYPbJ77wKa9t/qZz9txMJQI6MOKb/GvwE/J9hLnbTAEdDfUqBJy2Z/bdVOftvJxKAfJkCfuFx4RCbTP4vcN9p7AezH5Wmnf4LJvtvD0gA8uUUfvbfReAPgNeO8z5qUArM0n9nUPpvT0gAcmIhs//iFK5h8bz5t8EpcdZgt5U3uqwfXiaew3Ckeum/3ZAA5McBov/foZQW1kPccb6B36bTeIDpGpQClf7bBxKA/PBM/30AfAnhDvHZ0wEbAaYNq2wpcJ71zP6r9N9ekQDkh2f677LBNy02HhosZSWo3LGYEOxdO3cja/t1Dtf0XwAuQ6hU+m83JAA5sBDtvzN+9l/7M7D0O8Y2AlwL8NjjLiFuAr7o9kL5kyD9N6wCH0CoVPpvNyQA+eCc/hu+DtDecFokPhLkjsEh80/PceE3PEyc/jtaWftvJxKAfHBM/w3rwBew0X7T30ClwOcYZ1zpvwMgARiSdvqvOXXZDfAgwOdzjK4BWPwEWna61wuhuqVApf8OgARgSFrxmfkCfum/PwJftH8TYgnqltO9JoDpedar+H1xEnjd+R4rwPtVTP/tRhX/o0uFxcgpF/tvdoc/8Wy/uRXgesClEDBKLAV6u+hyJbP/nsuqAJ5cBy4XPd88kQAMj6f9FyN8QfzUzwgPgWtedyMmGU16zcdn1LaXuApLYf+tZPpvNyQAQ9CR/uvVW28twFUIT3b9jbXHBouG5V4KtPjTMfyNNHmTMP13Y7noyeaJBGAIvNN/A+Ee8PkcI+vtP5tlIgRYCrEe7cFhqlcKTJj+O1p5+28nEoDh8LT/Qoyc+mqLP79O3AvwYB9OFQ0Pntp/lf47CBKA4TiNb/rvdzy7AdjGrRRIrGpUphT41P6bJP23FvbfTiQAA5Io/fczYhLQZn4krg48mACm5nlkjvPKk9dJlv67Xgv7bycSgAExd/svq8BngY2tnvXvAjdwKAW2m4XCSOlLgXOsGTH7zzv99xZwaZbxWth/O5EADI6j/RdCPPr7+TyjW7zLw0PAsxnFlGGlLwW2aO0G/sr8TzB+zdZ7MZVHAjAA80/tv57ttK4Df9zqC4HwiLg3sN7PBXvF4r5GFU4FJrD/Ujv7bycSgAGw+OaYIT4v507m8vsGwo2tvj4fT6IthviY4HB/DgP7Pa6dMydxT/8NWfpvfey/nUgABsMt/beDT0N81u/GEn4JwfspebPQDvuv0n+HQAIwGD8HXvW6uGErYFfmt8+cu8nWFYI8KH0pUPbffJAA9Elm/z3vaP8FuAVhpzPnP2Q/PJgEpn7LgzKXAhPaf8Ny0ZP1QgLQJxaXxzM42X8BAuE74M87/LW7wE2fUiBjwPQYE6Nec8yBhPbf6qf/dkMC0D/e9l+Az3kaAdaF8ABYcjkUjBnxzeWyyTksC2yM427/DVBT+28nEoD+8Uz/hVji+ySw9qCHv3fNwMuccgxfl+MwHCKN/bc26b/dkAD0gX/6L2Q7/5/O7+A6m2N0zWIuwCOnoRyhvKXAE7jbf6mt/bcTCUB/tO2/nptjS/ToOguxROWSEEw8Ely6UmBH+q+3/fc28FEd7b+dSAD64y3gTed7fEHv3X9u7uAVGIY9lLAUmKX/zuCf/vsVNUr/7YYEoEfmov33rFf6b8aGwRXr3eDzAztuFg7MJL5HnQflKPEAkCe1tv92IgHoEfNP/yXAvQBXZmn1Wna6QzQEOczXxoHpBdbLVgqU/TdHJAA9Yknsv+Em/S07V3BrFopZPBVYmlLgXOxcfA7/yLJa2387kQD0jqv9N+OP9JX4G1aJm4YudoAAx0OJSoEtWnuJ9X/Zf3NCAtADaey/IQCf0Mcz/X0erAHXAsGlWSixTdhevzn3TSr77wd1tv92IgHogTT2Xx4Cl+do9fzc+U+8GIgrAK9n1bKVAmX/zRkJQG+ksP/+yGC20+s4NQs12GslaRaaOP33s6LnmwoJQG+cNv+a+LeB8McB/p1nQvCuUJJSYML038sQPOPWSoUEYAfa6b/4R2RdNmyQpp9uzUJDLHlOL8TwjaJ5nXTpv17mqtIhAdiBBOm/AI8MPurn+b+DeziVAi1+fxR+KvDXMZcgVfrvR7OM+xyyLCESgJ15E3/77+0weNfZh8CiR7fg7IpT+KfubssEEynTf78Y+ioVQgKwDZn99xzuO+HhW+uSANzDv10jegccmoUaxBVQ0aXABOm/oW3/dXmcKisSgG1oZfZfc14CB/gkDPgcP8fIBjEi3KtZ6MHsR5GcJO4BeLICvN8E+28nEoDtcbf/Zl1+P1xjY5hjvTfwbRbq/ezdlSz993xWBfBkicEfwyqLBGB7TgGvON/jNnD5vZj1PyjfE6sBuWOwmwJLgVn673n803+vQmiE/bcTCUAXMvvvjPmn4nxD3HwahmX8moWOG0y9V1wpUOm/jkgAupC98c/jaP/N7nPF4if4MNe4a/ExwGOEIwGmNxyPQe/AO0QR8OQOcHGW0UbYfzuRAHTnNeIjgCcPAlwKPBoq1isQHgRYcjoUCHC8iFLgPOvjwIzsv35IALpzGmf7b4jn/z+eY3Kod653s1DiJqD3m/A5DDtEXIU5fp8GiJt/tU7/7YYEYAuy9N8Lnum/ABZz574Z9jodzUK9EoIP4R/CsRVK/3VGArA1h4nWU8f03xBCNJ7ktXnn2Sx0H9EQlIyE6b+3gA9nGat1+m83JABb457+G6KH/4M5RvIy8NzEqRRIAaXAhOm/X9NjDHsdkQBsYuGp/dcz/ReLn9hXcrykZ7PQCWB6nrWU3y9K/02ABOB5XiTW/71PwH1qsQloXvwEfO/TLNRGDaaNlrcZp5NU6b+Ns/92IgF4niliBcCTNeADcl2yezYLhQBT5r8cB57Yf88ZliL9t3H2304kAM9zCvf037AMXMo5d+4RsOjYLPRo8A9FAZ7Yfy/gb/9tTPpvNyQAHaRJ/wWi8eRqnheci2JyrSalQKX/JkIC0EGK9N+My8RNwLxZMr9moftJVwpMlf6b9yqsckgAnuVV3NN/w0PgIjz2SPK9GfwSgl8gQSkwcfrvICnMtUIC8Cxn8P8mz4wnEx77dbdxahYaYrPQqVkeuX7PJEz/vdKk9N9uSAAy5gmTxOW/dyusL/EzntxhyJOF3TBsFJhuMeLdLDSB/TesAu/DustqqUpIADLa6b/mav8lAB/maP/djGezUIDjFlcCLvyKFQPOJLD/3gY+nGW8kfbfTiQAT3G3/5LZf72MJ1m82GKIAZceHAVzKwXuYtduYvnP22/guQqrFBIAnqT/njVn+2/2zOlmPAmsuiUEZxzBtxQo+29iJAA8Tf/F3/77GXH32YUFdgdiKdArIdi7WWiC9N+wguMqrGpIACLHcbf/hsz+G7xO7LVxaxZKFEqXkJS2/Rf/CPIl4GPne1QGCUAkRfrvMmnaTt8KTqVAe1IKvJ/7Rmnb/muY0n8T0ngBaKf/4p/+myp3bhmnZqHAKDA9woRHKTBh+q9bN+XK0XgByHz/M5bE/hs8S3Rt7uGUEBxiiXQan1JgKvvvxabbfztpvAAQ039T2H/fT5Q7t4rPOQMyi8Qxw3I1Sy2wMU46+28j03+7IQGIm38p7L9/SGE8McJj4FqIm445XxuAIyH/05KHSGP/bWz6bzcaLQDzidJ/iaaTJMaT2afNQr3KXPvJ3y9xglgCdCQ0Ov23G40WgMz4cxbn9F+i/Tdl2+nr+CUE7yHHZqG/ZbVt/33J+TW5BXzU1PTfbjRaAIjW3xT234uJjSduzUKJNt2pX7GUi2iOMZbK/vs10QIsOmisAMwmSv+lmLbTP+LULDSr00/v5qVcSoGWxP4bZP/tQmMFYCRL/6Xi9t8u3CP2CfDAgKmA5fK6BXjL3O2/ND79txuNFQAy+6/n2d+n9t8Nb/vvs3eNsWCeYRfHLTYLGYq5zP4b0th/G53+240mC0CC9N+2/Tdt22lj4xGxFOjVLDSXUmAr1v1nfO2/AWT/7UojBWAhs/9aGvtvrum/vTDH6DqxFOiVEHyQfE4FTuFu/yVL/5X9dysaKQDEN/55qpv+2wuezUL3AEOX7QzetngGwBOl/25DUwXgFZKl/64VlTt302K7sNzJOgQN5Z58l41R4JfEU4CeKP13G5oqAGeIy09PMuPJuFc81078EJyahQYYB6YXWB+4FBhgL9g50hzCkv23C40TgCz9t1b2360JWbPQ/DGsBUyDjQ9xmePEjVjP10D23x1onAC0039JYv91O5ffC/dxLgVCGLgUaNgp0qzClP67DY0TAJLaf1uFGU8Me2SxEuD1CPLSoM/v77ExAuEccTPRk69R+u+2NEoAsvTfc/7pvywBV4qc6yyttRAjwj1LgQMZeDZgT0h3CEv2321olAC06m3/3Yol/JqF7mXgUmCYxv34LyukP4RVORolAKRN/10uerLEaLC7TtfezcDP8HYKp3ThDmT/7YGmCUAK+2+ZjCe38EsIHgem5ljrq4w3H0uHZyyuxjy5Csj+uwONEYAs/fc8/vbfbylP7twd3CoRNgJMG62+SoEWN/5O41r/D5n9txSrsFLTGAFInP5blrbT93FKCM44bn0GeRh21OAt3x6s3CFND4bK0xgBIKb/OhtPeEg8/lsS40l4SDwV6FIKtLgJ2FcpL8Ab+Md/y/7bI00SgATpvyEznpQjd26Nx+1moS6fhCGeCOy5FDjPeot4+i/vVOFnR1WuVVipaYQALET770z97b/P8h6TAd+E4H30UQo0bBdwBt/2X5n9tyyrsHLTCAEgSfrvk7bTRdp/t+KG+TULfYE+ynkGh8z9FCalWoWVnaYIQAL7byir8eRW8EsIngCmZ+PSfkcCvBr8y7Cy//ZB7QWgw/57xPlWi5TTeLKM06lAYkVlqgW9Lul/Dhzwm6rsv/1SewFoxWXqBZpj/92MW7NQi09UU9mz/bYssD4B/MJ8Gou2KesqrLTUXgCIdtUU9t9LJTWePMT3WPAxeioF2n7glHP9fwn42PMGdaMJAvA2aey/JTWexGahOJUCiRt7vSzrj+Ga/99O/y3lKqy01FoAOtJ/HevOQInbTs89aRYaVp1usS/0tr9ywrDcegpugey/A1BrASC+8c8DubSx2oYi03974XqIz8ce7FgKnGWjRVyJeQaAlHgVVl7qLgCvkix3bq3MxpPvcUsItklg+t34Jt+SVmzDfgbfcxilXYWVmboLwGmUOweOzUIhjFr09nctBRp2CP8YNqX/DkBtBSBh+u+XEMpuPLmLX7NQAkyF+Hp34xVchfjJKqyoHgyVpbYCkCb9t23/LTT9t4dBhvvAkmODgqNg2wV8vGmYZwPQbBU2UVQPhspSWwEgHjt9y/cWIUv/LbfxxGIpcNHiTnnuVzc43K3P4kLsAHSSHLoJb8NXwJeO168ttRSAxOm/ZbT/bno9RteJXgCXhOAQ3/xbvtYGu7MDQF7fa2U9hFUJaikAmf03RfpvlYwnS4HglRD8YuhSCgxwOLiuxEp7CKsS1FIAaF76by/cxKkUSPT3T73L6lb7La8CngagSqzCykpdBeAUMQLMk6oZT37ALSHYxmIpcHQrw9Ub+Doxr0JQ+u+A1E4A5gmjpEn/rZrx5CccS4HAFNEU9IR3WR8z+FkvpwUHo53+y7LjvGpN7QQg241OlP5bavvvJoJrs9AAx8NzWf+2m1gB8CrFVm0VVjpqJwAksf9SBfvvc2N2bhZ6mE1L/QCHApxwnFPVVmGlo44CkCr996OS23+fYY4R72ahB3i+FPgyA/cP7InLRFETA1IrAcjsvzP4t52qqvHErVlo1urr6KY/O+F3FLtt/12v0iqsdNRKADLjzzlL03a6isaTG7glBNsug6nf8/8G0QEY6//m5QBU+m8O1EoASJL+W+ncObdmocBYgOkvmGmXAieJBiCv77FS9WCoKrURgNlo/z2Lf/pvlY0njs1CMeKJv7b78iB+EWBt+6/Sf4ekNgIwkqX/WpL031AV++8mwgpw3fEGx8FeePrr3puGDDCPqq7CSkVtBIAk9l+qbjxZxde7cATYm/36NccjwFVehZWKOglAAvtvWAYuVdV4kh0Lvhbizw7X54DFhqEAbwaCVxjLZ4DsvzlQCwGYy+y/TU7/7YVZRl2bhQbYE+CledYngZ/h4sYM65S3B0PlqIUAtDL7L0nSfyufO3cdv4Tg3cBxww4Ar5tPNXYZ2X9zoxYCQNL038q3nb6F0x5Gdipwirj555UB+CfgU6drN466CMAvcLf/ktl/K288cUwIphViQvAbPmlMAeIqrEKHsMpN5QVg4Wn6r+y/vbEC3HBMz5wGzgSf/w+l/+aM9zNzCg4D5/BP//2wovbfZzDCg4BdMwJOL9nLwCPDem0Z3g9K/82ZOghAAvtvfYwnG2w8NkYWic1CPf7/XyFuynqsLmX/zZlKPwJk6b9nE6X/Xil6vnkwH/cwFoNTQrBh+wybdri07L8OVFoAOtJ/J4e91g7UzXjiWQoEl2eL+qzCykSlBYC483/G9xa1NJ7cwi8h2AvZfx2ougC8TfQAeLJM/YwnP+BXCvTiKvVahZWCygpAlv47Q5r037oZT7wTgnOmnf67sVz0SOpGZQWgI/3XsZLRNp5UKf23p3k9iHOqTDXtDnBxltE6rcJKQWUFgHTpvx/UMHfuEfFQUFVcjd8RHwFEzlRZAFLZf2uXOzfHyDpwzasU6MDHNTiEVUoqKQCJ7b91NZ4sAfeLHsTOhLquwkpBJQWAaPw5i7/9t87Gk5vA3aIH0QPZKqw6PRiqRFUF4A1cW05DA4wnt4nlwLJT51VY4VROABKn/35c9Hwd+Qko+eom1H0VVjiVE4C06b9UNP23J1ybheZE3VdhhVM5AUD233xmGHsELob4KVtW6r4KK5wqCoDsvzlwj8U1ohegzKXACvdgqAaVEoC2/dfS2H8rm/7bC//CK64JwcPTXoVVtgdDJaiUAGSx3+fxDzK50pDcuZu4NQsdmmVqvgorA5USAJKm/66X9Y2RJ7fxaxY6LEr/TUDVBOC0+cVNt2mS8WQZv2ahw1LDQ1jlozICMB/tvzPI/psj4R6+zUIHHVeTVmGFUplQUEuX/tsY44nF045lPGTTPoRV5hJlLajMCgDZf3NnhMePiQLg0ix0COrSg6H0VEIAZtOm/zYmd+43TIYQzUCrRY/lKU/sv2Xdm6gVlRCAtv0X//TfJubOXadcpcBGrcKKphICQGw2edr5HlnuXH3tv134nhi5VRYatQormqoIwCnghO8twh2aaTxZplzHgq9CaNoqrDCqUgV4APxHNt5Bd4a3+3dG/OS5VPREC2DZ4N+BT3j2Nerndc5ptz4E4L+Q/TcZVRGA/wb+x/keG5n/vGGEFbB/Jd/V4DCCsDHLSBNMWEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhCgtfwGgTF415D87hwAAAABJRU5ErkJggg==';
        const iconFilePath = path.join(literalpath, '/app.ico');
        fs.writeFileSync(iconFilePath, Buffer.from(icoData, 'base64'), 'binary');
        if (!fs.existsSync(process.env.APPDATA + '/Microsoft/Windows/Start Menu/Programs/NovAMPP.lnk')) {
            const shortcutPath = path.join(process.env.APPDATA, '/Microsoft/Windows/Start Menu/Programs/NovAMPP.lnk');
            const target = path.join(literalpath, '/NovAMPP.exe');
            const icon = path.join(literalpath, '/app.ico');
            exec(`powershell "$shortcut = (New-Object -ComObject WScript.Shell).CreateShortcut('${shortcutPath}'); $shortcut.TargetPath = '${target}'; $shortcut.IconLocation = '${icon}'; $shortcut.Save()"`, (error, stdout, stderr) => {
                if (error) {
                    console.error(`Error creating shortcut: ${error.message}`);
                    return;
                }
                console.log('Shortcut created successfully');
            });
        }
    };
    if (!fs.existsSync(literalpath)) fs.mkdirSync(literalpath);
    if (!fs.existsSync(literalpath + '/docker')) fs.mkdirSync(literalpath + '/docker');
    const dockerComposePath = path.join(literalpath, '/docker/docker-compose.yaml');
    if (!fs.existsSync(dockerComposePath)) {
        dialog.showMessageBox({
            type: 'error',
            title: 'Compose - NovAMPP',
            message: 'Docker Compose files are missing',
            detail: 'Please download them from GitLab and place them in the Docker folder, then restart NovAMPP.',
            buttons: ['OK', 'Go to GitLab', 'Open Folder']
        }).then((response) => {
            if (response.response === 0) {
                app.exit();
                app.quit();
            } else if (response.response === 1) {
                const command = process.platform === 'win32' ? 'start https://git.zeusteam.dev/nova/novampp/-/releases' : process.platform === 'darwin' ? 'open https://git.zeusteam.dev/nova/novampp/-/releases' : 'xdg-open https://git.zeusteam.dev/nova/novampp/-/releases';
                exec(command, (error, stdout, stderr) => {
                    if (error) {
                        console.log('Failed to open GitLab page');
                    } else {
                        console.log('GitLab page opened');
                        app.exit();
                        app.quit();
                    }
                });
            } else {
                if (process.platform === 'win32') {
                    exec('start ' + literalpath + '/docker', (error, stdout, stderr) => {
                        if (error) {
                            console.log('Failed to open Docker folder');
                        } else {
                            console.log('Docker folder opened');
                            app.exit();
                            app.quit();
                        }
                    });
                } else if (process.platform === 'darwin') {
                    exec('open ' + literalpath + '/docker', (error, stdout, stderr) => {
                        if (error) {
                            console.log('Failed to open Docker folder');
                        } else {
                            console.log('Docker folder opened');
                            app.exit();
                            app.quit();
                        }
                    });
                } else if (process.platform === 'linux') {
                    exec('xdg-open ' + literalpath + '/docker', (error, stdout, stderr) => {
                        if (error) {
                            console.log('Failed to open Docker folder');
                        } else {
                            console.log('Docker folder opened');
                            app.exit();
                            app.quit();
                        }
                    });
                };
            }
        });
    };
    //if (!fs.existsSync(dockerComposePath)) {
    //    const zipUrl = 'https://git.zeusteam.dev/nova/novampp/-/releases/latest/download/docker.zip';
    //    const zipFilePath = path.join(literalpath, '/docker/docker.zip');
    //    const extractPath = path.join(literalpath, '/docker');
    //    axios({
    //        method: 'get',
    //        url: zipUrl,
    //        responseType: 'stream'
    //    }).then(response => {
    //        const writer = fs.createWriteStream(zipFilePath);
    //        response.data.pipe(writer);
    //        writer.on('finish', () => {
    //            fs.createReadStream(zipFilePath)
    //                .pipe(unzipper.Extract({ path: extractPath }))
    //                .on('close', () => {
    //                    fs.unlinkSync(zipFilePath);
    //                    console.log('Compose files extracted successfully');
    //                });
    //        });
    //    }).catch(error => {
    //        console.log('Failed to download the Compose files');
    //    });
    //};
    if (fs.existsSync(path.join(literalpath, '/docker/docker.zip'))) {
        fs.unlinkSync(path.join(literalpath, '/docker/docker.zip'));
        console.log('docker.zip deleted');
    };
    if (fs.existsSync(path.join(literalpath, '/docker/docker-installer.exe'))) {
        fs.unlinkSync(path.join(literalpath, '/docker/docker-installer.exe'));
        console.log('docker-installer.exe deleted');
    };
    if (fs.existsSync(path.join(literalpath, '/docker/docker.dmg'))) {
        fs.unlinkSync(path.join(literalpath, '/docker/docker.dmg'));
        console.log('docker.dmg deleted');
    };
    if (fs.existsSync(path.join(literalpath, '/docker/docker-installer.deb'))) {
        fs.unlinkSync(path.join(literalpath, '/docker/docker-installer.deb'));
        console.log('docker-installer.deb deleted');
    };
    if (fs.existsSync(path.join(literalpath, '/docker/docker-installer.rpm'))) {
        fs.unlinkSync(path.join(literalpath, '/docker/docker-installer.rpm'));
        console.log('docker-installer.rpm deleted');
    };
    if (!fs.existsSync(literalpath)) {
        fs.mkdirSync(literalpath);
    } else if (!fs.existsSync(literalpath + '/docker')) {
        fs.mkdirSync(literalpath + '/docker');
    } else if (!fs.existsSync(literalpath + '/docker/builds')) {
        fs.mkdirSync(literalpath + '/docker/builds');
    } else if (!fs.existsSync(literalpath + '/docker/data')) {
        fs.mkdirSync(literalpath + '/docker/data');
    } else if (!fs.existsSync(literalpath + '/docker/data/httpd')) {
        fs.mkdirSync(literalpath + '/docker/data/httpd');
    } else if (!fs.existsSync(literalpath + '/docker/data/mariadb')) {
        fs.mkdirSync(literalpath + '/docker/data/mariadb');
    } else if (!fs.existsSync(literalpath + '/docker/builds/httpd')) {
        fs.mkdirSync(literalpath + '/docker/builds/httpd');
    } else if (!fs.existsSync(literalpath + '/docker/builds/mariadb')) {
        fs.mkdirSync(literalpath + '/docker/builds/mariadb');
    } else if (!fs.existsSync(literalpath + '/docker/builds/httpd/apache2')) {
        fs.mkdirSync(literalpath + '/docker/builds/httpd/apache2');
    } else if (!fs.existsSync(literalpath + '/docker/builds/httpd/apache2/conf-available')) {
        fs.mkdirSync(literalpath + '/docker/builds/httpd/apache2/conf-available');
    } else if (!fs.existsSync(literalpath + '/docker/builds/httpd/apache2/mods-available')) {
        fs.mkdirSync(literalpath + '/docker/builds/httpd/apache2/mods-available');
    } else if (!fs.existsSync(literalpath + '/docker/builds/httpd/apache2/sites-available')) {
        fs.mkdirSync(literalpath + '/docker/builds/httpd/apache2/sites-available');
    } else if (!fs.existsSync(literalpath + '/docker/builds/httpd/apache2/conf-enabled')) {
        fs.mkdirSync(literalpath + '/docker/builds/httpd/apache2/conf-enabled');
    } else if (!fs.existsSync(literalpath + '/docker/builds/httpd/apache2/mods-enabled')) {
        fs.mkdirSync(literalpath + '/docker/builds/httpd/apache2/mods-enabled');
    } else if (!fs.existsSync(literalpath + '/docker/builds/httpd/apache2/sites-enabled')) {
        fs.mkdirSync(literalpath + '/docker/builds/httpd/apache2/sites-enabled');
    };
};
function checkargs() {
    if (process.argv.length === 2) {
        switch (process.argv[1]) {
            case '--terminal':
                if (global.ConsoleOpen === undefined) {
                    global.ConsoleOpen = true;
                    app.whenReady().then(() => {
                        const newWindow = new BrowserWindow({
                            width: 900,
                            height: 600,
                            resizable: false,
                            webPreferences: {
                                preload: path.join(__dirname, './src/preload.js'),
                                nodeIntegration: true,
                                contextIsolation: true,
                            }
                        });

                        newWindow.loadFile(path.join(__dirname, './src/main/console.html'));
                        newWindow.setMenuBarVisibility(false);
                        newWindow.setIcon(path.join(iconPath));
                        const originalConsoleLog = console.log;

                        console.log = function (...args) {
                            const logMessage = args.join(' ');
                            newWindow.webContents.send('console-message', logMessage);
                            originalConsoleLog.apply(console, args);
                        };
                    });
                };
        }
    };
    if (debugMode && global.ConsoleOpen === undefined) {
        global.ConsoleOpen = true;
        app.whenReady().then(() => {
            const newWindow = new BrowserWindow({
                width: 900,
                height: 600,
                resizable: false,
                webPreferences: {
                    preload: path.join(__dirname, './src/preload.js'),
                    nodeIntegration: true,
                    contextIsolation: true,
                }
            });
    
            newWindow.loadFile(path.join(__dirname, './src/main/console.html'));
            newWindow.setMenuBarVisibility(false);
            newWindow.setIcon(path.join(iconPath));
            const originalConsoleLog = console.log;
    
            console.log = function (...args) {
                const logMessage = args.join(' ');
                newWindow.webContents.send('console-message', logMessage);
                originalConsoleLog.apply(console, args);
            };
        });
    };
};
async function checkforupdates() {
    const appVersion = app.getVersion();
    const otherVersionUrl = 'https://git.zeusteam.dev/nova/novampp/-/raw/master/package.json';
    try {
        const response = await axios.get(otherVersionUrl);
        const otherVersion = response.data.version;

        if (appVersion === otherVersion) {
            console.log('App version is up to date');
        } else if (appVersion < otherVersion) {
            console.log('App version is older');
            dialog.showMessageBox({
                type: 'info',
                title: 'Update Available - NovAMPP',
                message: 'A new version of NovAMPP is available. Please update to the latest version.',
                detail: `Current Version: ${appVersion}\nLatest Version: ${otherVersion}`,
                buttons: ['Don\'t Update', 'Update']
            }).then((response) => {
                if (response.response === 1) {
                    const command = process.platform === 'win32' ? 'start https://git.zeusteam.dev/nova/novampp/-/releases' : process.platform === 'darwin' ? 'open https://git.zeusteam.dev/nova/novampp/-/releases' : 'xdg-open https://git.zeusteam.dev/nova/novampp/-/releases';
                    exec(command, (error, stdout, stderr) => {
                        if (error) {
                            console.log('Failed to open update page');
                        } else {
                            console.log('Update page opened');
                            app.exit();
                            app.quit();
                        }
                    });
                } else {
                    console.log('User chose not to update');
                };
            });
        } else {
            console.log('I have no idea what happened here');
        }
    } catch (error) {
        console.log('Failed to fetch latest version');
    }
};
//if (debugMode) {
//    function createLogger(logFilePath) {
//        const logStream = fs.createWriteStream(logFilePath, { flags: 'a' });
//    
//        const originalConsoleLog = console.log;
//    
//        console.log = function (...args) {
//            const logMessage = args.join(' ');
//            logStream.write(`${logMessage}\n`);
//            originalConsoleLog.apply(console, args);
//        };
//    
//        return {
//            close: function () {
//                logStream.end();
//            }
//        };
//    };
//    function log() {
//        if (!fs.existsSync(path.join(__dirname, './logs'))) {
//            fs.mkdirSync(path.join(__dirname, './logs'));
//        }
//        const logFilePath = path.join(__dirname, `./logs/`, `${Date.now()}.log`);
//        const logger = createLogger(logFilePath);
//        return logger;
//    };
//    log();
//    console.log('Debug logging is enabled');
//};

function createWindow() {
    const win = new BrowserWindow({
        width: 800,
        height: 600,
        webPreferences: {
            preload: path.join(__dirname, './src/preload.js'),
            nodeIntegration: true,
            contextIsolation: true,
        }
    });
    win.on('close', (event) => {
        event.preventDefault();
        win.hide();
    });
    win.setIcon(iconPath);
    isDockerInstalled().then((dockerinstalled) => {
        if (forceMenu) {
            console.log('Forcing menu page');
            win.loadFile(path.join(__dirname, './src/menu/menu.html'));
        } else if (forceDocker) {
            console.log('Forcing Docker install page');
            win.loadFile(path.join(__dirname, './src/setup/installdocker.html'));
        } else if (dockerinstalled === "true") {
            win.loadFile(path.join(__dirname, './src/menu/menu.html'));
        } else {
            win.loadFile(path.join(__dirname, './src/setup/installdocker.html'));
        };
    }).catch((error) => {
        console.log('Failed to check if Docker is installed');
    });
    //win.webContents.openDevTools();
    return win;
};

function createTrayMenu(win) {
    const trayIcon = new Tray(iconPath);
    const trayMenu = Menu.buildFromTemplate([
        { label: 'NovAMPP Manager', enabled: false },
        { label: 'Show / Hide', click: () => {
            if (win) {
                if (win.isVisible()) {
                    win.hide();
                } else {
                    win.show();
                }
            } else {
                createWindow();
            }
        }},
        { label: 'Restart Compose', click: () => {
            exec('docker compose down && docker compose up -d', { cwd: literalpath + "./docker/" }, (error, stdout, stderr) => {
                if (error) {
                    console.log('Failed to restart Compose');
                } else {
                    console.log('Compose restarted');
                };
            });
        }},
        { type: 'separator' },
        { label: 'Quit', click: () => {
            app.exit();
            app.quit();
        }},
    ]);
    trayIcon.setContextMenu(trayMenu);
};

app.whenReady().then(async () => {
    await checkargs();
    await registeripc();
    console.log('Starting NovAMPP...');
    startupchecks();
    installdocker();
    checkforupdates();
    const win = createWindow();
    createTrayMenu(win);
    app.on('activate', function () {
        if (BrowserWindow.getAllWindows().length === 0) createWindow();
    });
    app.on('browser-window-created', function (event, window) {
        window.setIcon(iconPath);
    });
});

app.on('window-all-closed', function () {
    app.exit();
    app.quit();
});