version: '3'
services:
    novampp-httpd:
        build: ./builds/httpd/
        container_name: novampp-httpd
        image: novampp-httpd
        volumes:
            - ./data/httpd:/usr/local/apache2/htdocs/
            - ./data/httpd:/var/www/html/
        restart: always
        ports:
            - 80:80
            - 443:443
        networks:
            novampp:
                ipv4_address: 172.20.0.2
    novampp-mariadb:
        build: ./builds/mariadb/
        container_name: novampp-mariadb
        image: novampp-mariadb
        volumes:
          - ./data/mariadb:/var/lib/mysql
        restart: always
        environment:
            # Edit root password for MDB here, highly recommended for production environments
            - MARIADB_ROOT_PASSWORD=root
        ports:
            - 3306:3306
        networks:
            novampp:
                ipv4_address: 172.20.0.3
    novampp-phpmyadmin:
        build: ./builds/phpmyadmin/
        container_name: novampp-phpmyadmin
        image: novampp-phpmyadmin
        restart: always
        environment:
            # Edit root password for PMA here, highly recommended for production environments
            - PMA_ARBITRARY=1
            - PMA_USER=root
            - PMA_PASSWORD=root
        ports:
            - 8080:80
        networks:
            novampp:
                ipv4_address: 172.20.0.4
networks:
    novampp:
        name: novampp
        driver: bridge
        ipam:
            config:
                - subnet: 172.20.0.0/16
                  gateway: 172.20.0.1