version: '3'
services:
    novampp-httpd:
        container_name: novampp-httpd
        image: 
        volumes:
            - ./data/httpd:/var/www/html
        restart: always
        ports:
            - 80:80
            - 443:443
        networks:
            - novampp
    novampp-mysql:
        container_name: novampp-mysql
        image: 
        volumes:
            - ./data/mysql:/var/lib/mysql
        restart: always
        ports:
            - 3306:3306
        networks:
            - novampp
networks:
    novampp:
        name: novampp